name: Deploy Quartz site to GitHub Pages

on:
  push:
    branches:
      - main

env:
  # from: https://github.com/saberzero1/quartz-themes?tab=readme-ov-file#supported-themes
  THEME_NAME: abecedarium

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive # Fetch content in `content/` submodule
          fetch-depth: 0 # Fetch all history for git info
          token: ${{ secrets.DOCS_PAT }}

      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 22

      - name: Install Dependencies
        run: npm ci

      - name: Fetch Quartz theme
        run: curl -s -S https://raw.githubusercontent.com/saberzero1/quartz-themes/master/action.sh | bash -s -- $THEME_NAME

      - name: Build Quartz
        run: npx quartz build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
